/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Chart: typeof import('./src/components/Chart/index.vue')['default']
    'Chart_副本': typeof import('./src/components/Chart_副本.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ContextMenu: typeof import('./src/components/contextMenu/index.vue')['default']
    copy: typeof import('./src/components/SvgIcon/index copy.vue')['default']
    DesktopPageSwitch: typeof import('./src/components/TheHeader/components/desktop-page-switch.vue')['default']
    Echarts: typeof import('./src/components/echarts/index.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/GlobalSetting/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    MobilePageSwitch: typeof import('./src/components/TheHeader/components/mobile-page-switch.vue')['default']
    PageSwitch: typeof import('./src/components/TheHeader/components/page-switch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Test: typeof import('./src/components/SvgIcon/test.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter/index.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader/index.vue')['default']
    ThemeSwitch: typeof import('./src/components/TheHeader/components/theme-switch.vue')['default']
    VideoPlay: typeof import('./src/components/VideoPlay/index.vue')['default']
  }
}
