<script lang="ts" setup>
import hljs from 'highlight.js'

import typescript from 'highlight.js/lib/languages/typescript'

import {
  nextTick,
  ref,
  watch,
} from 'vue'

import 'highlight.js/styles/default.min.css'

// 注册语言
hljs.registerLanguage('typescript', typescript)

/** 当前模式 */
const type = ref('code')

/** 是否格式错误 */
const isError = ref<boolean>(false)

/** 用户输入的 JSON 字符串 */
const inputJson = ref<string>('')

/** 生成的 TypeScript 类型字符串 */
const outputClass = ref('')

/**
 * 将首字母转为大写
 * @param  str - 输入字符串
 * @returns  首字母大写后的字符串
 */
function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

/**
 * 获取值对应的 TypeScript 类型
 * @param  value - 任意值
 * @returns  TypeScript 类型
 */
function getTypeScriptType(value: any): string {
  if (typeof value === 'string') {
    return 'string'
  }

  if (typeof value === 'number') {
    return 'number'
  }

  if (typeof value === 'boolean') {
    return 'boolean'
  }

  if (Array.isArray(value)) {
    return value.length > 0 ? `${getTypeScriptType(value[0])}[]` : 'any[]'
  }

  if (typeof value === 'object' && value !== null) {
    return 'object'
  }

  return 'any'
}

/**
 * 根据 JSON 对象生成 TypeScript 类型定义
 * @param {any} jsonObj - JSON 对象
 * @param {string} typeName - 类型名
 * @returns {string} 类型定义字符串
 */
function generateTypeScriptType(jsonObj: any, typeName: string = 'AutoGenerated'): string {
  let result = `type ${typeName} = {\n`

  let subTypes = ''

  for (const key in jsonObj) {
    const value = jsonObj[key]

    const fieldName = /^[a-z_$][\w$]*$/i.test(key) ? key : `"${key}"`

    if (typeof value === 'object' && !Array.isArray(value) && value !== null) {
      const nestedTypeName = capitalizeFirstLetter(key)

      result += `  ${fieldName}: ${nestedTypeName};\n`
      subTypes += generateTypeScriptType(value, nestedTypeName)
    }
    else if (Array.isArray(value) && value.length > 0) {
      const itemTypeName = `${capitalizeFirstLetter(key)}Item`

      result += `  ${fieldName}: ${itemTypeName}[];\n`

      if (typeof value[0] === 'object' && value[0] !== null) {
        subTypes += generateTypeScriptType(value[0], itemTypeName)
      }
      else {
        subTypes += `type ${itemTypeName} = ${getTypeScriptType(value[0])};\n\n`
      }
    }
    else {
      result += `  ${fieldName}: ${getTypeScriptType(value)};\n`
    }
  }

  result += '};\n\n'
  return result + subTypes
}

/**
 * 对代码块重新应用 highlight.js 高亮
 */
function applyHighlight() {
  nextTick(() => {
    const codeElement = document.getElementById('code')

    if (codeElement) {
      codeElement.className = 'typescript'
      codeElement.innerHTML = outputClass.value
      codeElement.removeAttribute('data-highlighted')
      hljs.highlightElement(codeElement)
    }
  })
}

/**
 * 格式化 JSON 输入，并生成 TypeScript 类型
 */
function formatJson() {
  isError.value = false
  try {
    const jsonObj = JSON.parse(inputJson.value)

    outputClass.value = generateTypeScriptType(jsonObj)
    applyHighlight()
  }
  catch {
    isError.value = true
    outputClass.value = ''
  }
}

// 页面初始化时格式化一次
formatJson()

// 监听输入变化实时格式化
watch(inputJson, (newVal) => {
  if (newVal.trim()) {
    formatJson()
  }
  else {
    outputClass.value = ''
  }
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center justify-between"
    >
      <div
        class="flex items-center gap-5"
      >
        <el-radio-group
          v-model="type"
        >
          <el-radio-button
            value="code"
            label="JSON 转TS"
          />
        </el-radio-group>
      </div>

      <BaseButton
        v-if="!isError && inputJson.length > 0"
        v-copy="{
          text: outputClass,
          message: '生成的 Ts 类型 已经复制到剪切板',
        }"
        :size="40"
        icon="copy"
        tooltip-content="点击复制"
      />
    </div>

    <div
      class="h-[calc(100vh-200px)] flex items-center justify-center gap-15"
    >
      <el-input
        v-model="inputJson"
        type="textarea"
        placeholder="请输入 JSON 数据"
        class="!h-full !flex-1"
        :input-style="{ height: '100%' }"
      />

      <div
        class="h-full flex flex-1 items-center justify-center border rounded-2 bg-white !relative"
      >
        <el-alert
          v-if="isError && inputJson.length > 0"
          title="JSON 格式错误，请检查输入"
          type="error"
          class="!w-1/2"
        />

        <pre
          v-if="outputClass.length > 0"
          class="h-full w-full overflow-y-auto"
        >
           <code
              id="code"
               class="typescript border rounded-2 bg-white p-3 !h-full !w-full"
             >
            {{ outputClass }}
            </code>
         </pre>

      </div>
    </div>
  </div>
</template>
