/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../../components/AppProvider/index.vue')['default']
    BackHomeButton: typeof import('./../../components/Button/back-home-button/index.vue')['default']
    BaseButton: typeof import('./../../components/Button/base-button/index.vue')['default']
    copy: typeof import('./../../components/MusicPlayer/index copy.vue')['default']
    DownloadButton: typeof import('./../../components/Button/download-button/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Github: typeof import('./../../components/Github/index.vue')['default']
    IconLoading: typeof import('./../../components/Loading/icon-loading/index.vue')['default']
    IconLogo: typeof import('./../../components/Logo/icon-logo/index.vue')['default']
    'Index copy': typeof import('./../../components/MusicPlayer/index copy.vue')['default']
    LinkButton: typeof import('./../../components/Button/link-button/index.vue')['default']
    MousePosition: typeof import('./../../components/MousePosition/index.vue')['default']
    MusicPlayer: typeof import('./../../components/MusicPlayer/index.vue')['default']
    PageLoading: typeof import('./../../components/Loading/page-loading/index.vue')['default']
    PreviewImg: typeof import('./../../components/PreviewImg/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../../components/SvgIcon/index.vue')['default']
    SwitchTheme: typeof import('./../../components/SwitchTheme/index.vue')['default']
    TextLogo: typeof import('./../../components/Logo/text-logo/index.vue')['default']
    TypeIt: typeof import('./../../components/TypeIt/index.vue')['default']
    VideoPlayer: typeof import('./../../components/VideoPlayer/index.vue')['default']
    VueEcharts: typeof import('./../../components/VueEcharts/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AppProvider: typeof import('./../../components/AppProvider/index.vue')['default']
  const BackHomeButton: typeof import('./../../components/Button/back-home-button/index.vue')['default']
  const BaseButton: typeof import('./../../components/Button/base-button/index.vue')['default']
  const copy: typeof import('./../../components/MusicPlayer/index copy.vue')['default']
  const DownloadButton: typeof import('./../../components/Button/download-button/index.vue')['default']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const Github: typeof import('./../../components/Github/index.vue')['default']
  const IconLoading: typeof import('./../../components/Loading/icon-loading/index.vue')['default']
  const IconLogo: typeof import('./../../components/Logo/icon-logo/index.vue')['default']
  const 'Index copy': typeof import('./../../components/MusicPlayer/index copy.vue')['default']
  const LinkButton: typeof import('./../../components/Button/link-button/index.vue')['default']
  const MousePosition: typeof import('./../../components/MousePosition/index.vue')['default']
  const MusicPlayer: typeof import('./../../components/MusicPlayer/index.vue')['default']
  const PageLoading: typeof import('./../../components/Loading/page-loading/index.vue')['default']
  const PreviewImg: typeof import('./../../components/PreviewImg/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../../components/SvgIcon/index.vue')['default']
  const SwitchTheme: typeof import('./../../components/SwitchTheme/index.vue')['default']
  const TextLogo: typeof import('./../../components/Logo/text-logo/index.vue')['default']
  const TypeIt: typeof import('./../../components/TypeIt/index.vue')['default']
  const VideoPlayer: typeof import('./../../components/VideoPlayer/index.vue')['default']
  const VueEcharts: typeof import('./../../components/VueEcharts/index.vue')['default']
}