/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasLoader: typeof import('./../components/CanvasLoader/index.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    Github: typeof import('./../components/Github/index.vue')['default']
    GlobalSetting: typeof import('./../components/GlobalSetting/index.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    Logo: typeof import('./../components/Logo/index.vue')['default']
    MusicPlayer: typeof import('./../components/MusicPlayer/index.vue')['default']
    PreviewImg: typeof import('./../components/PreviewImg/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    VideoPlayer: typeof import('./../components/VideoPlayer/index.vue')['default']
  }
}
