/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/blog/creativity/calendar/': RouteRecordInfo<'/blog/creativity/calendar/', '/blog/creativity/calendar', Record<never, never>, Record<never, never>>,
    '/blog/creativity/calendar/left': RouteRecordInfo<'/blog/creativity/calendar/left', '/blog/creativity/calendar/left', Record<never, never>, Record<never, never>>,
    '/blog/creativity/calendar/right': RouteRecordInfo<'/blog/creativity/calendar/right', '/blog/creativity/calendar/right', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/': RouteRecordInfo<'/blog/creativity/clock/', '/blog/creativity/clock', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/components/left': RouteRecordInfo<'/blog/creativity/clock/components/left', '/blog/creativity/clock/components/left', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/components/right': RouteRecordInfo<'/blog/creativity/clock/components/right', '/blog/creativity/clock/components/right', Record<never, never>, Record<never, never>>,
    '/blog/creativity/muYu/': RouteRecordInfo<'/blog/creativity/muYu/', '/blog/creativity/muYu', Record<never, never>, Record<never, never>>,
    '/blog/media/music/': RouteRecordInfo<'/blog/media/music/', '/blog/media/music', Record<never, never>, Record<never, never>>,
    '/blog/media/video/': RouteRecordInfo<'/blog/media/video/', '/blog/media/video', Record<never, never>, Record<never, never>>,
    '/blog/media/voice/': RouteRecordInfo<'/blog/media/voice/', '/blog/media/voice', Record<never, never>, Record<never, never>>,
    '/blog/media/wallpaper/': RouteRecordInfo<'/blog/media/wallpaper/', '/blog/media/wallpaper', Record<never, never>, Record<never, never>>,
    '/blog/news/game/hok/': RouteRecordInfo<'/blog/news/game/hok/', '/blog/news/game/hok', Record<never, never>, Record<never, never>>,
    '/blog/news/movie/': RouteRecordInfo<'/blog/news/movie/', '/blog/news/movie', Record<never, never>, Record<never, never>>,
    '/blog/news/movie/components/parse/': RouteRecordInfo<'/blog/news/movie/components/parse/', '/blog/news/movie/components/parse', Record<never, never>, Record<never, never>>,
    '/blog/news/price/cigarette/': RouteRecordInfo<'/blog/news/price/cigarette/', '/blog/news/price/cigarette', Record<never, never>, Record<never, never>>,
    '/blog/news/price/gold/': RouteRecordInfo<'/blog/news/price/gold/', '/blog/news/price/gold', Record<never, never>, Record<never, never>>,
    '/blog/news/price/oil/': RouteRecordInfo<'/blog/news/price/oil/', '/blog/news/price/oil', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/': RouteRecordInfo<'/blog/news/weather/', '/blog/news/weather', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/climate/': RouteRecordInfo<'/blog/news/weather/components/climate/', '/blog/news/weather/components/climate', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/meter/': RouteRecordInfo<'/blog/news/weather/components/meter/', '/blog/news/weather/components/meter', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/passedChart/': RouteRecordInfo<'/blog/news/weather/components/passedChart/', '/blog/news/weather/components/passedChart', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/tempChart/': RouteRecordInfo<'/blog/news/weather/components/tempChart/', '/blog/news/weather/components/tempChart', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/account/': RouteRecordInfo<'/blog/socialEngineering/account/', '/blog/socialEngineering/account', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/complain/': RouteRecordInfo<'/blog/socialEngineering/complain/', '/blog/socialEngineering/complain', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/domain/': RouteRecordInfo<'/blog/socialEngineering/domain/', '/blog/socialEngineering/domain', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/licensePlate/': RouteRecordInfo<'/blog/socialEngineering/licensePlate/', '/blog/socialEngineering/licensePlate', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/logistic/': RouteRecordInfo<'/blog/socialEngineering/logistic/', '/blog/socialEngineering/logistic', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/loveSpeech/': RouteRecordInfo<'/blog/socialEngineering/loveSpeech/', '/blog/socialEngineering/loveSpeech', Record<never, never>, Record<never, never>>,
    '/blog/test/api/': RouteRecordInfo<'/blog/test/api/', '/blog/test/api', Record<never, never>, Record<never, never>>,
    '/blog/test/component/': RouteRecordInfo<'/blog/test/component/', '/blog/test/component', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/base64/': RouteRecordInfo<'/blog/tool/codec/base64/', '/blog/tool/codec/base64', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/base64/modal': RouteRecordInfo<'/blog/tool/codec/base64/modal', '/blog/tool/codec/base64/modal', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/md5/': RouteRecordInfo<'/blog/tool/codec/md5/', '/blog/tool/codec/md5', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/morse/': RouteRecordInfo<'/blog/tool/codec/morse/', '/blog/tool/codec/morse', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/morse/modal': RouteRecordInfo<'/blog/tool/codec/morse/modal', '/blog/tool/codec/morse/modal', Record<never, never>, Record<never, never>>,
    '/blog/tool/jsonFormatter/': RouteRecordInfo<'/blog/tool/jsonFormatter/', '/blog/tool/jsonFormatter', Record<never, never>, Record<never, never>>,
    '/blog/tool/network/dns/': RouteRecordInfo<'/blog/tool/network/dns/', '/blog/tool/network/dns', Record<never, never>, Record<never, never>>,
    '/blog/tool/network/http/': RouteRecordInfo<'/blog/tool/network/http/', '/blog/tool/network/http', Record<never, never>, Record<never, never>>,
    '/blog/tool/qrcode/': RouteRecordInfo<'/blog/tool/qrcode/', '/blog/tool/qrcode', Record<never, never>, Record<never, never>>,
    '/blog/workbench/': RouteRecordInfo<'/blog/workbench/', '/blog/workbench', Record<never, never>, Record<never, never>>,
    '/error/403/': RouteRecordInfo<'/error/403/', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404/': RouteRecordInfo<'/error/404/', '/error/404', Record<never, never>, Record<never, never>>,
    '/error/500/': RouteRecordInfo<'/error/500/', '/error/500', Record<never, never>, Record<never, never>>,
    '/error/redirect/': RouteRecordInfo<'/error/redirect/', '/error/redirect', Record<never, never>, Record<never, never>>,
    '/garage/': RouteRecordInfo<'/garage/', '/garage', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/': RouteRecordInfo<'/garage/threeContainer/', '/garage/threeContainer', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/index copy': RouteRecordInfo<'/garage/threeContainer/index copy', '/garage/threeContainer/index copy', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/index copy 2': RouteRecordInfo<'/garage/threeContainer/index copy 2', '/garage/threeContainer/index copy 2', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer copy 2/': RouteRecordInfo<'/garage/threeContainer copy 2/', '/garage/threeContainer copy 2', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/': RouteRecordInfo<'/garage/uiContainer/', '/garage/uiContainer', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/components/bar/': RouteRecordInfo<'/garage/uiContainer/components/bar/', '/garage/uiContainer/components/bar', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/components/loading/': RouteRecordInfo<'/garage/uiContainer/components/loading/', '/garage/uiContainer/components/loading', Record<never, never>, Record<never, never>>,
    '/home/about/': RouteRecordInfo<'/home/about/', '/home/about', Record<never, never>, Record<never, never>>,
    '/home/about/components/info': RouteRecordInfo<'/home/about/components/info', '/home/about/components/info', Record<never, never>, Record<never, never>>,
    '/home/about/components/intro': RouteRecordInfo<'/home/about/components/intro', '/home/about/components/intro', Record<never, never>, Record<never, never>>,
    '/home/about/components/map': RouteRecordInfo<'/home/about/components/map', '/home/about/components/map', Record<never, never>, Record<never, never>>,
    '/home/contact/': RouteRecordInfo<'/home/contact/', '/home/contact', Record<never, never>, Record<never, never>>,
    '/home/resume/': RouteRecordInfo<'/home/resume/', '/home/resume', Record<never, never>, Record<never, never>>,
    '/home/work/': RouteRecordInfo<'/home/work/', '/home/work', Record<never, never>, Record<never, never>>,
    '/home/work/components/experience/': RouteRecordInfo<'/home/work/components/experience/', '/home/work/components/experience', Record<never, never>, Record<never, never>>,
    '/home/work/components/project/': RouteRecordInfo<'/home/work/components/project/', '/home/work/components/project', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
  }
}
