/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/creativity/calendar/': RouteRecordInfo<
      '/admin/creativity/calendar/',
      '/admin/creativity/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/calendar/left': RouteRecordInfo<
      '/admin/creativity/calendar/left',
      '/admin/creativity/calendar/left',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/calendar/right': RouteRecordInfo<
      '/admin/creativity/calendar/right',
      '/admin/creativity/calendar/right',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/clock/': RouteRecordInfo<
      '/admin/creativity/clock/',
      '/admin/creativity/clock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/clock/components/left': RouteRecordInfo<
      '/admin/creativity/clock/components/left',
      '/admin/creativity/clock/components/left',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/clock/components/right': RouteRecordInfo<
      '/admin/creativity/clock/components/right',
      '/admin/creativity/clock/components/right',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/creativity/muYu/': RouteRecordInfo<
      '/admin/creativity/muYu/',
      '/admin/creativity/muYu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dev/jsonFormatter/': RouteRecordInfo<
      '/admin/dev/jsonFormatter/',
      '/admin/dev/jsonFormatter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dev/jsonToTypeScript/': RouteRecordInfo<
      '/admin/dev/jsonToTypeScript/',
      '/admin/dev/jsonToTypeScript',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/av/': RouteRecordInfo<
      '/admin/media/av/',
      '/admin/media/av',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/av/site_btn': RouteRecordInfo<
      '/admin/media/av/site_btn',
      '/admin/media/av/site_btn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/copywriting/': RouteRecordInfo<
      '/admin/media/copywriting/',
      '/admin/media/copywriting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/music/': RouteRecordInfo<
      '/admin/media/music/',
      '/admin/media/music',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/video/': RouteRecordInfo<
      '/admin/media/video/',
      '/admin/media/video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/voice/': RouteRecordInfo<
      '/admin/media/voice/',
      '/admin/media/voice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/media/wallpaper/': RouteRecordInfo<
      '/admin/media/wallpaper/',
      '/admin/media/wallpaper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/boxOffice/': RouteRecordInfo<
      '/admin/news/boxOffice/',
      '/admin/news/boxOffice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/boxOffice/components/parse/': RouteRecordInfo<
      '/admin/news/boxOffice/components/parse/',
      '/admin/news/boxOffice/components/parse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/game/hok/': RouteRecordInfo<
      '/admin/news/game/hok/',
      '/admin/news/game/hok',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/itNews/': RouteRecordInfo<
      '/admin/news/itNews/',
      '/admin/news/itNews',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/price/cigarette/': RouteRecordInfo<
      '/admin/news/price/cigarette/',
      '/admin/news/price/cigarette',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/price/gold/': RouteRecordInfo<
      '/admin/news/price/gold/',
      '/admin/news/price/gold',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/price/oil/': RouteRecordInfo<
      '/admin/news/price/oil/',
      '/admin/news/price/oil',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/weather/': RouteRecordInfo<
      '/admin/news/weather/',
      '/admin/news/weather',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/weather/components/climate/': RouteRecordInfo<
      '/admin/news/weather/components/climate/',
      '/admin/news/weather/components/climate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/weather/components/meter/': RouteRecordInfo<
      '/admin/news/weather/components/meter/',
      '/admin/news/weather/components/meter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/weather/components/passedChart/': RouteRecordInfo<
      '/admin/news/weather/components/passedChart/',
      '/admin/news/weather/components/passedChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/news/weather/components/tempChart/': RouteRecordInfo<
      '/admin/news/weather/components/tempChart/',
      '/admin/news/weather/components/tempChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/account/': RouteRecordInfo<
      '/admin/socialEngineering/account/',
      '/admin/socialEngineering/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/complain/': RouteRecordInfo<
      '/admin/socialEngineering/complain/',
      '/admin/socialEngineering/complain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/domain/': RouteRecordInfo<
      '/admin/socialEngineering/domain/',
      '/admin/socialEngineering/domain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/licensePlate/': RouteRecordInfo<
      '/admin/socialEngineering/licensePlate/',
      '/admin/socialEngineering/licensePlate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/logistic/': RouteRecordInfo<
      '/admin/socialEngineering/logistic/',
      '/admin/socialEngineering/logistic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/socialEngineering/loveSpeech/': RouteRecordInfo<
      '/admin/socialEngineering/loveSpeech/',
      '/admin/socialEngineering/loveSpeech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/test/api/': RouteRecordInfo<
      '/admin/test/api/',
      '/admin/test/api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/test/component/': RouteRecordInfo<
      '/admin/test/component/',
      '/admin/test/component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/codec/base64/': RouteRecordInfo<
      '/admin/tool/codec/base64/',
      '/admin/tool/codec/base64',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/codec/base64/modal': RouteRecordInfo<
      '/admin/tool/codec/base64/modal',
      '/admin/tool/codec/base64/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/codec/md5/': RouteRecordInfo<
      '/admin/tool/codec/md5/',
      '/admin/tool/codec/md5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/codec/morse/': RouteRecordInfo<
      '/admin/tool/codec/morse/',
      '/admin/tool/codec/morse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/codec/morse/modal': RouteRecordInfo<
      '/admin/tool/codec/morse/modal',
      '/admin/tool/codec/morse/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/network/dns/': RouteRecordInfo<
      '/admin/tool/network/dns/',
      '/admin/tool/network/dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/network/http/': RouteRecordInfo<
      '/admin/tool/network/http/',
      '/admin/tool/network/http',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tool/qrcode/': RouteRecordInfo<
      '/admin/tool/qrcode/',
      '/admin/tool/qrcode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/workbench/': RouteRecordInfo<
      '/admin/workbench/',
      '/admin/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/workbench/MapChart': RouteRecordInfo<
      '/admin/workbench/MapChart',
      '/admin/workbench/MapChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/': RouteRecordInfo<
      '/bigScreen/',
      '/bigScreen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/components/mapScene/': RouteRecordInfo<
      '/bigScreen/components/mapScene/',
      '/bigScreen/components/mapScene',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/components/mCard/': RouteRecordInfo<
      '/bigScreen/components/mCard/',
      '/bigScreen/components/mCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/components/mCountTo/vue-countTo': RouteRecordInfo<
      '/bigScreen/components/mCountTo/vue-countTo',
      '/bigScreen/components/mCountTo/vue-countTo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/components/mPie/': RouteRecordInfo<
      '/bigScreen/components/mPie/',
      '/bigScreen/components/mPie',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/components/mSvglineAnimation/': RouteRecordInfo<
      '/bigScreen/components/mSvglineAnimation/',
      '/bigScreen/components/mSvglineAnimation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-count-card/': RouteRecordInfo<
      '/bigScreen/modules/global-count-card/',
      '/bigScreen/modules/global-count-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-decorative-line/': RouteRecordInfo<
      '/bigScreen/modules/global-decorative-line/',
      '/bigScreen/modules/global-decorative-line',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-footer/': RouteRecordInfo<
      '/bigScreen/modules/global-footer/',
      '/bigScreen/modules/global-footer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-header/': RouteRecordInfo<
      '/bigScreen/modules/global-header/',
      '/bigScreen/modules/global-header',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-left-chart/': RouteRecordInfo<
      '/bigScreen/modules/global-left-chart/',
      '/bigScreen/modules/global-left-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-left-chart/BulkCommoditySalesChart': RouteRecordInfo<
      '/bigScreen/modules/global-left-chart/BulkCommoditySalesChart',
      '/bigScreen/modules/global-left-chart/BulkCommoditySalesChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-left-chart/DistrictEconomicIncome': RouteRecordInfo<
      '/bigScreen/modules/global-left-chart/DistrictEconomicIncome',
      '/bigScreen/modules/global-left-chart/DistrictEconomicIncome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-left-chart/EconomicTrendChart': RouteRecordInfo<
      '/bigScreen/modules/global-left-chart/EconomicTrendChart',
      '/bigScreen/modules/global-left-chart/EconomicTrendChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-left-chart/YearlyEconomyTrend': RouteRecordInfo<
      '/bigScreen/modules/global-left-chart/YearlyEconomyTrend',
      '/bigScreen/modules/global-left-chart/YearlyEconomyTrend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-menu/': RouteRecordInfo<
      '/bigScreen/modules/global-menu/',
      '/bigScreen/modules/global-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-radar/': RouteRecordInfo<
      '/bigScreen/modules/global-radar/',
      '/bigScreen/modules/global-radar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-right-chart/': RouteRecordInfo<
      '/bigScreen/modules/global-right-chart/',
      '/bigScreen/modules/global-right-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-right-chart/ElectricityUsage': RouteRecordInfo<
      '/bigScreen/modules/global-right-chart/ElectricityUsage',
      '/bigScreen/modules/global-right-chart/ElectricityUsage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-right-chart/ProportionPopulationConsumption': RouteRecordInfo<
      '/bigScreen/modules/global-right-chart/ProportionPopulationConsumption',
      '/bigScreen/modules/global-right-chart/ProportionPopulationConsumption',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-right-chart/PurposeSpecialFunds': RouteRecordInfo<
      '/bigScreen/modules/global-right-chart/PurposeSpecialFunds',
      '/bigScreen/modules/global-right-chart/PurposeSpecialFunds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bigScreen/modules/global-right-chart/QuarterlyGrowthSituation': RouteRecordInfo<
      '/bigScreen/modules/global-right-chart/QuarterlyGrowthSituation',
      '/bigScreen/modules/global-right-chart/QuarterlyGrowthSituation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/': RouteRecordInfo<
      '/blog/',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/components/renderer/': RouteRecordInfo<
      '/blog/components/renderer/',
      '/blog/components/renderer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/components/sidebar/': RouteRecordInfo<
      '/blog/components/sidebar/',
      '/blog/components/sidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact/': RouteRecordInfo<
      '/contact/',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403/': RouteRecordInfo<
      '/error/403/',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404/': RouteRecordInfo<
      '/error/404/',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/500/': RouteRecordInfo<
      '/error/500/',
      '/error/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/redirect/': RouteRecordInfo<
      '/error/redirect/',
      '/error/redirect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/': RouteRecordInfo<
      '/garage/',
      '/garage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/threeContainer/': RouteRecordInfo<
      '/garage/threeContainer/',
      '/garage/threeContainer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/threeContainer/index copy': RouteRecordInfo<
      '/garage/threeContainer/index copy',
      '/garage/threeContainer/index copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/threeContainer/index copy 2': RouteRecordInfo<
      '/garage/threeContainer/index copy 2',
      '/garage/threeContainer/index copy 2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/threeContainer copy 2/': RouteRecordInfo<
      '/garage/threeContainer copy 2/',
      '/garage/threeContainer copy 2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/uiContainer/': RouteRecordInfo<
      '/garage/uiContainer/',
      '/garage/uiContainer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/uiContainer/components/bar/': RouteRecordInfo<
      '/garage/uiContainer/components/bar/',
      '/garage/uiContainer/components/bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/garage/uiContainer/components/loading/': RouteRecordInfo<
      '/garage/uiContainer/components/loading/',
      '/garage/uiContainer/components/loading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/components/info': RouteRecordInfo<
      '/home/components/info',
      '/home/components/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/components/intro': RouteRecordInfo<
      '/home/components/intro',
      '/home/components/intro',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/': RouteRecordInfo<
      '/love/',
      '/love',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/police/identityQuery/detail/': RouteRecordInfo<
      '/police/identityQuery/detail/',
      '/police/identityQuery/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/police/identityQuery/result/': RouteRecordInfo<
      '/police/identityQuery/result/',
      '/police/identityQuery/result',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/police/identityQuery/search/': RouteRecordInfo<
      '/police/identityQuery/search/',
      '/police/identityQuery/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/police/login/': RouteRecordInfo<
      '/police/login/',
      '/police/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/': RouteRecordInfo<
      '/test/',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/work/': RouteRecordInfo<
      '/work/',
      '/work',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/work/components/experience/': RouteRecordInfo<
      '/work/components/experience/',
      '/work/components/experience',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/work/components/project/': RouteRecordInfo<
      '/work/components/project/',
      '/work/components/project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/admin/creativity/calendar/index.vue': {
      routes:
        | '/admin/creativity/calendar/'
      views:
        | never
    }
    'src/pages/admin/creativity/calendar/left.vue': {
      routes:
        | '/admin/creativity/calendar/left'
      views:
        | never
    }
    'src/pages/admin/creativity/calendar/right.vue': {
      routes:
        | '/admin/creativity/calendar/right'
      views:
        | never
    }
    'src/pages/admin/creativity/clock/index.vue': {
      routes:
        | '/admin/creativity/clock/'
      views:
        | never
    }
    'src/pages/admin/creativity/clock/components/left.vue': {
      routes:
        | '/admin/creativity/clock/components/left'
      views:
        | never
    }
    'src/pages/admin/creativity/clock/components/right.vue': {
      routes:
        | '/admin/creativity/clock/components/right'
      views:
        | never
    }
    'src/pages/admin/creativity/muYu/index.vue': {
      routes:
        | '/admin/creativity/muYu/'
      views:
        | never
    }
    'src/pages/admin/dev/jsonFormatter/index.vue': {
      routes:
        | '/admin/dev/jsonFormatter/'
      views:
        | never
    }
    'src/pages/admin/dev/jsonToTypeScript/index.vue': {
      routes:
        | '/admin/dev/jsonToTypeScript/'
      views:
        | never
    }
    'src/pages/admin/media/av/index.vue': {
      routes:
        | '/admin/media/av/'
      views:
        | never
    }
    'src/pages/admin/media/av/site_btn.vue': {
      routes:
        | '/admin/media/av/site_btn'
      views:
        | never
    }
    'src/pages/admin/media/copywriting/index.vue': {
      routes:
        | '/admin/media/copywriting/'
      views:
        | never
    }
    'src/pages/admin/media/music/index.vue': {
      routes:
        | '/admin/media/music/'
      views:
        | never
    }
    'src/pages/admin/media/video/index.vue': {
      routes:
        | '/admin/media/video/'
      views:
        | never
    }
    'src/pages/admin/media/voice/index.vue': {
      routes:
        | '/admin/media/voice/'
      views:
        | never
    }
    'src/pages/admin/media/wallpaper/index.vue': {
      routes:
        | '/admin/media/wallpaper/'
      views:
        | never
    }
    'src/pages/admin/news/boxOffice/index.vue': {
      routes:
        | '/admin/news/boxOffice/'
      views:
        | never
    }
    'src/pages/admin/news/boxOffice/components/parse/index.vue': {
      routes:
        | '/admin/news/boxOffice/components/parse/'
      views:
        | never
    }
    'src/pages/admin/news/game/hok/index.vue': {
      routes:
        | '/admin/news/game/hok/'
      views:
        | never
    }
    'src/pages/admin/news/itNews/index.vue': {
      routes:
        | '/admin/news/itNews/'
      views:
        | never
    }
    'src/pages/admin/news/price/cigarette/index.vue': {
      routes:
        | '/admin/news/price/cigarette/'
      views:
        | never
    }
    'src/pages/admin/news/price/gold/index.vue': {
      routes:
        | '/admin/news/price/gold/'
      views:
        | never
    }
    'src/pages/admin/news/price/oil/index.vue': {
      routes:
        | '/admin/news/price/oil/'
      views:
        | never
    }
    'src/pages/admin/news/weather/index.vue': {
      routes:
        | '/admin/news/weather/'
      views:
        | never
    }
    'src/pages/admin/news/weather/components/climate/index.vue': {
      routes:
        | '/admin/news/weather/components/climate/'
      views:
        | never
    }
    'src/pages/admin/news/weather/components/meter/index.vue': {
      routes:
        | '/admin/news/weather/components/meter/'
      views:
        | never
    }
    'src/pages/admin/news/weather/components/passedChart/index.vue': {
      routes:
        | '/admin/news/weather/components/passedChart/'
      views:
        | never
    }
    'src/pages/admin/news/weather/components/tempChart/index.vue': {
      routes:
        | '/admin/news/weather/components/tempChart/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/account/index.vue': {
      routes:
        | '/admin/socialEngineering/account/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/complain/index.vue': {
      routes:
        | '/admin/socialEngineering/complain/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/domain/index.vue': {
      routes:
        | '/admin/socialEngineering/domain/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/licensePlate/index.vue': {
      routes:
        | '/admin/socialEngineering/licensePlate/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/logistic/index.vue': {
      routes:
        | '/admin/socialEngineering/logistic/'
      views:
        | never
    }
    'src/pages/admin/socialEngineering/loveSpeech/index.vue': {
      routes:
        | '/admin/socialEngineering/loveSpeech/'
      views:
        | never
    }
    'src/pages/admin/test/api/index.vue': {
      routes:
        | '/admin/test/api/'
      views:
        | never
    }
    'src/pages/admin/test/component/index.vue': {
      routes:
        | '/admin/test/component/'
      views:
        | never
    }
    'src/pages/admin/tool/codec/base64/index.vue': {
      routes:
        | '/admin/tool/codec/base64/'
      views:
        | never
    }
    'src/pages/admin/tool/codec/base64/modal.vue': {
      routes:
        | '/admin/tool/codec/base64/modal'
      views:
        | never
    }
    'src/pages/admin/tool/codec/md5/index.vue': {
      routes:
        | '/admin/tool/codec/md5/'
      views:
        | never
    }
    'src/pages/admin/tool/codec/morse/index.vue': {
      routes:
        | '/admin/tool/codec/morse/'
      views:
        | never
    }
    'src/pages/admin/tool/codec/morse/modal.vue': {
      routes:
        | '/admin/tool/codec/morse/modal'
      views:
        | never
    }
    'src/pages/admin/tool/network/dns/index.vue': {
      routes:
        | '/admin/tool/network/dns/'
      views:
        | never
    }
    'src/pages/admin/tool/network/http/index.vue': {
      routes:
        | '/admin/tool/network/http/'
      views:
        | never
    }
    'src/pages/admin/tool/qrcode/index.vue': {
      routes:
        | '/admin/tool/qrcode/'
      views:
        | never
    }
    'src/pages/admin/workbench/index.vue': {
      routes:
        | '/admin/workbench/'
      views:
        | never
    }
    'src/pages/admin/workbench/MapChart.vue': {
      routes:
        | '/admin/workbench/MapChart'
      views:
        | never
    }
    'src/pages/bigScreen/index.vue': {
      routes:
        | '/bigScreen/'
      views:
        | never
    }
    'src/pages/bigScreen/components/mapScene/index.vue': {
      routes:
        | '/bigScreen/components/mapScene/'
      views:
        | never
    }
    'src/pages/bigScreen/components/mCard/index.vue': {
      routes:
        | '/bigScreen/components/mCard/'
      views:
        | never
    }
    'src/pages/bigScreen/components/mCountTo/vue-countTo.vue': {
      routes:
        | '/bigScreen/components/mCountTo/vue-countTo'
      views:
        | never
    }
    'src/pages/bigScreen/components/mPie/index.vue': {
      routes:
        | '/bigScreen/components/mPie/'
      views:
        | never
    }
    'src/pages/bigScreen/components/mSvglineAnimation/index.vue': {
      routes:
        | '/bigScreen/components/mSvglineAnimation/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-count-card/index.vue': {
      routes:
        | '/bigScreen/modules/global-count-card/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-decorative-line/index.vue': {
      routes:
        | '/bigScreen/modules/global-decorative-line/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-footer/index.vue': {
      routes:
        | '/bigScreen/modules/global-footer/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-header/index.vue': {
      routes:
        | '/bigScreen/modules/global-header/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-left-chart/index.vue': {
      routes:
        | '/bigScreen/modules/global-left-chart/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-left-chart/BulkCommoditySalesChart.vue': {
      routes:
        | '/bigScreen/modules/global-left-chart/BulkCommoditySalesChart'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-left-chart/DistrictEconomicIncome.vue': {
      routes:
        | '/bigScreen/modules/global-left-chart/DistrictEconomicIncome'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-left-chart/EconomicTrendChart.vue': {
      routes:
        | '/bigScreen/modules/global-left-chart/EconomicTrendChart'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-left-chart/YearlyEconomyTrend.vue': {
      routes:
        | '/bigScreen/modules/global-left-chart/YearlyEconomyTrend'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-menu/index.vue': {
      routes:
        | '/bigScreen/modules/global-menu/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-radar/index.vue': {
      routes:
        | '/bigScreen/modules/global-radar/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-right-chart/index.vue': {
      routes:
        | '/bigScreen/modules/global-right-chart/'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-right-chart/ElectricityUsage.vue': {
      routes:
        | '/bigScreen/modules/global-right-chart/ElectricityUsage'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-right-chart/ProportionPopulationConsumption.vue': {
      routes:
        | '/bigScreen/modules/global-right-chart/ProportionPopulationConsumption'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-right-chart/PurposeSpecialFunds.vue': {
      routes:
        | '/bigScreen/modules/global-right-chart/PurposeSpecialFunds'
      views:
        | never
    }
    'src/pages/bigScreen/modules/global-right-chart/QuarterlyGrowthSituation.vue': {
      routes:
        | '/bigScreen/modules/global-right-chart/QuarterlyGrowthSituation'
      views:
        | never
    }
    'src/pages/blog/index.vue': {
      routes:
        | '/blog/'
      views:
        | never
    }
    'src/pages/blog/components/renderer/index.vue': {
      routes:
        | '/blog/components/renderer/'
      views:
        | never
    }
    'src/pages/blog/components/sidebar/index.vue': {
      routes:
        | '/blog/components/sidebar/'
      views:
        | never
    }
    'src/pages/contact/index.vue': {
      routes:
        | '/contact/'
      views:
        | never
    }
    'src/pages/error/403/index.vue': {
      routes:
        | '/error/403/'
      views:
        | never
    }
    'src/pages/error/404/index.vue': {
      routes:
        | '/error/404/'
      views:
        | never
    }
    'src/pages/error/500/index.vue': {
      routes:
        | '/error/500/'
      views:
        | never
    }
    'src/pages/error/redirect/index.vue': {
      routes:
        | '/error/redirect/'
      views:
        | never
    }
    'src/pages/garage/index.vue': {
      routes:
        | '/garage/'
      views:
        | never
    }
    'src/pages/garage/threeContainer/index.vue': {
      routes:
        | '/garage/threeContainer/'
      views:
        | never
    }
    'src/pages/garage/threeContainer/index copy.vue': {
      routes:
        | '/garage/threeContainer/index copy'
      views:
        | never
    }
    'src/pages/garage/threeContainer/index copy 2.vue': {
      routes:
        | '/garage/threeContainer/index copy 2'
      views:
        | never
    }
    'src/pages/garage/threeContainer copy 2/index.vue': {
      routes:
        | '/garage/threeContainer copy 2/'
      views:
        | never
    }
    'src/pages/garage/uiContainer/index.vue': {
      routes:
        | '/garage/uiContainer/'
      views:
        | never
    }
    'src/pages/garage/uiContainer/components/bar/index.vue': {
      routes:
        | '/garage/uiContainer/components/bar/'
      views:
        | never
    }
    'src/pages/garage/uiContainer/components/loading/index.vue': {
      routes:
        | '/garage/uiContainer/components/loading/'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/home/components/info.vue': {
      routes:
        | '/home/components/info'
      views:
        | never
    }
    'src/pages/home/components/intro.vue': {
      routes:
        | '/home/components/intro'
      views:
        | never
    }
    'src/pages/love/index.vue': {
      routes:
        | '/love/'
      views:
        | never
    }
    'src/pages/police/identityQuery/detail/index.vue': {
      routes:
        | '/police/identityQuery/detail/'
      views:
        | never
    }
    'src/pages/police/identityQuery/result/index.vue': {
      routes:
        | '/police/identityQuery/result/'
      views:
        | never
    }
    'src/pages/police/identityQuery/search/index.vue': {
      routes:
        | '/police/identityQuery/search/'
      views:
        | never
    }
    'src/pages/police/login/index.vue': {
      routes:
        | '/police/login/'
      views:
        | never
    }
    'src/pages/test/index.vue': {
      routes:
        | '/test/'
      views:
        | never
    }
    'src/pages/work/index.vue': {
      routes:
        | '/work/'
      views:
        | never
    }
    'src/pages/work/components/experience/index.vue': {
      routes:
        | '/work/components/experience/'
      views:
        | never
    }
    'src/pages/work/components/project/index.vue': {
      routes:
        | '/work/components/project/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
