/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/bigScreen/': RouteRecordInfo<'/bigScreen/', '/bigScreen', Record<never, never>, Record<never, never>>,
    '/bigScreen/comments/mapScene/': RouteRecordInfo<'/bigScreen/comments/mapScene/', '/bigScreen/comments/mapScene', Record<never, never>, Record<never, never>>,
    '/bigScreen/comments/mCountCard/': RouteRecordInfo<'/bigScreen/comments/mCountCard/', '/bigScreen/comments/mCountCard', Record<never, never>, Record<never, never>>,
    '/bigScreen/comments/mHeader/': RouteRecordInfo<'/bigScreen/comments/mHeader/', '/bigScreen/comments/mHeader', Record<never, never>, Record<never, never>>,
    '/bigScreen/comments/mMenu/': RouteRecordInfo<'/bigScreen/comments/mMenu/', '/bigScreen/comments/mMenu', Record<never, never>, Record<never, never>>,
    '/bigScreen/comments/mMenuItem/': RouteRecordInfo<'/bigScreen/comments/mMenuItem/', '/bigScreen/comments/mMenuItem', Record<never, never>, Record<never, never>>,
    '/blog/creativity/calendar/': RouteRecordInfo<'/blog/creativity/calendar/', '/blog/creativity/calendar', Record<never, never>, Record<never, never>>,
    '/blog/creativity/calendar/left': RouteRecordInfo<'/blog/creativity/calendar/left', '/blog/creativity/calendar/left', Record<never, never>, Record<never, never>>,
    '/blog/creativity/calendar/right': RouteRecordInfo<'/blog/creativity/calendar/right', '/blog/creativity/calendar/right', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/': RouteRecordInfo<'/blog/creativity/clock/', '/blog/creativity/clock', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/components/left': RouteRecordInfo<'/blog/creativity/clock/components/left', '/blog/creativity/clock/components/left', Record<never, never>, Record<never, never>>,
    '/blog/creativity/clock/components/right': RouteRecordInfo<'/blog/creativity/clock/components/right', '/blog/creativity/clock/components/right', Record<never, never>, Record<never, never>>,
    '/blog/creativity/muYu/': RouteRecordInfo<'/blog/creativity/muYu/', '/blog/creativity/muYu', Record<never, never>, Record<never, never>>,
    '/blog/dev/jsonFormatter/': RouteRecordInfo<'/blog/dev/jsonFormatter/', '/blog/dev/jsonFormatter', Record<never, never>, Record<never, never>>,
    '/blog/dev/jsonToTypeScript/': RouteRecordInfo<'/blog/dev/jsonToTypeScript/', '/blog/dev/jsonToTypeScript', Record<never, never>, Record<never, never>>,
    '/blog/media/av/': RouteRecordInfo<'/blog/media/av/', '/blog/media/av', Record<never, never>, Record<never, never>>,
    '/blog/media/av/site_btn': RouteRecordInfo<'/blog/media/av/site_btn', '/blog/media/av/site_btn', Record<never, never>, Record<never, never>>,
    '/blog/media/copywriting/': RouteRecordInfo<'/blog/media/copywriting/', '/blog/media/copywriting', Record<never, never>, Record<never, never>>,
    '/blog/media/music/': RouteRecordInfo<'/blog/media/music/', '/blog/media/music', Record<never, never>, Record<never, never>>,
    '/blog/media/video/': RouteRecordInfo<'/blog/media/video/', '/blog/media/video', Record<never, never>, Record<never, never>>,
    '/blog/media/voice/': RouteRecordInfo<'/blog/media/voice/', '/blog/media/voice', Record<never, never>, Record<never, never>>,
    '/blog/media/wallpaper/': RouteRecordInfo<'/blog/media/wallpaper/', '/blog/media/wallpaper', Record<never, never>, Record<never, never>>,
    '/blog/news/boxOffice/': RouteRecordInfo<'/blog/news/boxOffice/', '/blog/news/boxOffice', Record<never, never>, Record<never, never>>,
    '/blog/news/boxOffice/components/parse/': RouteRecordInfo<'/blog/news/boxOffice/components/parse/', '/blog/news/boxOffice/components/parse', Record<never, never>, Record<never, never>>,
    '/blog/news/game/hok/': RouteRecordInfo<'/blog/news/game/hok/', '/blog/news/game/hok', Record<never, never>, Record<never, never>>,
    '/blog/news/itNews/': RouteRecordInfo<'/blog/news/itNews/', '/blog/news/itNews', Record<never, never>, Record<never, never>>,
    '/blog/news/price/cigarette/': RouteRecordInfo<'/blog/news/price/cigarette/', '/blog/news/price/cigarette', Record<never, never>, Record<never, never>>,
    '/blog/news/price/gold/': RouteRecordInfo<'/blog/news/price/gold/', '/blog/news/price/gold', Record<never, never>, Record<never, never>>,
    '/blog/news/price/oil/': RouteRecordInfo<'/blog/news/price/oil/', '/blog/news/price/oil', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/': RouteRecordInfo<'/blog/news/weather/', '/blog/news/weather', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/climate/': RouteRecordInfo<'/blog/news/weather/components/climate/', '/blog/news/weather/components/climate', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/meter/': RouteRecordInfo<'/blog/news/weather/components/meter/', '/blog/news/weather/components/meter', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/passedChart/': RouteRecordInfo<'/blog/news/weather/components/passedChart/', '/blog/news/weather/components/passedChart', Record<never, never>, Record<never, never>>,
    '/blog/news/weather/components/tempChart/': RouteRecordInfo<'/blog/news/weather/components/tempChart/', '/blog/news/weather/components/tempChart', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/account/': RouteRecordInfo<'/blog/socialEngineering/account/', '/blog/socialEngineering/account', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/complain/': RouteRecordInfo<'/blog/socialEngineering/complain/', '/blog/socialEngineering/complain', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/domain/': RouteRecordInfo<'/blog/socialEngineering/domain/', '/blog/socialEngineering/domain', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/licensePlate/': RouteRecordInfo<'/blog/socialEngineering/licensePlate/', '/blog/socialEngineering/licensePlate', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/logistic/': RouteRecordInfo<'/blog/socialEngineering/logistic/', '/blog/socialEngineering/logistic', Record<never, never>, Record<never, never>>,
    '/blog/socialEngineering/loveSpeech/': RouteRecordInfo<'/blog/socialEngineering/loveSpeech/', '/blog/socialEngineering/loveSpeech', Record<never, never>, Record<never, never>>,
    '/blog/test/api/': RouteRecordInfo<'/blog/test/api/', '/blog/test/api', Record<never, never>, Record<never, never>>,
    '/blog/test/component/': RouteRecordInfo<'/blog/test/component/', '/blog/test/component', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/base64/': RouteRecordInfo<'/blog/tool/codec/base64/', '/blog/tool/codec/base64', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/base64/modal': RouteRecordInfo<'/blog/tool/codec/base64/modal', '/blog/tool/codec/base64/modal', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/md5/': RouteRecordInfo<'/blog/tool/codec/md5/', '/blog/tool/codec/md5', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/morse/': RouteRecordInfo<'/blog/tool/codec/morse/', '/blog/tool/codec/morse', Record<never, never>, Record<never, never>>,
    '/blog/tool/codec/morse/modal': RouteRecordInfo<'/blog/tool/codec/morse/modal', '/blog/tool/codec/morse/modal', Record<never, never>, Record<never, never>>,
    '/blog/tool/network/dns/': RouteRecordInfo<'/blog/tool/network/dns/', '/blog/tool/network/dns', Record<never, never>, Record<never, never>>,
    '/blog/tool/network/http/': RouteRecordInfo<'/blog/tool/network/http/', '/blog/tool/network/http', Record<never, never>, Record<never, never>>,
    '/blog/tool/qrcode/': RouteRecordInfo<'/blog/tool/qrcode/', '/blog/tool/qrcode', Record<never, never>, Record<never, never>>,
    '/blog/workbench/': RouteRecordInfo<'/blog/workbench/', '/blog/workbench', Record<never, never>, Record<never, never>>,
    '/blog/workbench/MapChart': RouteRecordInfo<'/blog/workbench/MapChart', '/blog/workbench/MapChart', Record<never, never>, Record<never, never>>,
    '/blog/workbench/测试/MapChart copy 3': RouteRecordInfo<'/blog/workbench/测试/MapChart copy 3', '/blog/workbench/测试/MapChart copy 3', Record<never, never>, Record<never, never>>,
    '/command/identityQuery/detail/': RouteRecordInfo<'/command/identityQuery/detail/', '/command/identityQuery/detail', Record<never, never>, Record<never, never>>,
    '/command/identityQuery/result/': RouteRecordInfo<'/command/identityQuery/result/', '/command/identityQuery/result', Record<never, never>, Record<never, never>>,
    '/command/identityQuery/search/': RouteRecordInfo<'/command/identityQuery/search/', '/command/identityQuery/search', Record<never, never>, Record<never, never>>,
    '/command/login/': RouteRecordInfo<'/command/login/', '/command/login', Record<never, never>, Record<never, never>>,
    '/error/403/': RouteRecordInfo<'/error/403/', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404/': RouteRecordInfo<'/error/404/', '/error/404', Record<never, never>, Record<never, never>>,
    '/error/500/': RouteRecordInfo<'/error/500/', '/error/500', Record<never, never>, Record<never, never>>,
    '/error/redirect/': RouteRecordInfo<'/error/redirect/', '/error/redirect', Record<never, never>, Record<never, never>>,
    '/garage/': RouteRecordInfo<'/garage/', '/garage', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/': RouteRecordInfo<'/garage/threeContainer/', '/garage/threeContainer', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/index copy': RouteRecordInfo<'/garage/threeContainer/index copy', '/garage/threeContainer/index copy', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer/index copy 2': RouteRecordInfo<'/garage/threeContainer/index copy 2', '/garage/threeContainer/index copy 2', Record<never, never>, Record<never, never>>,
    '/garage/threeContainer copy 2/': RouteRecordInfo<'/garage/threeContainer copy 2/', '/garage/threeContainer copy 2', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/': RouteRecordInfo<'/garage/uiContainer/', '/garage/uiContainer', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/components/bar/': RouteRecordInfo<'/garage/uiContainer/components/bar/', '/garage/uiContainer/components/bar', Record<never, never>, Record<never, never>>,
    '/garage/uiContainer/components/loading/': RouteRecordInfo<'/garage/uiContainer/components/loading/', '/garage/uiContainer/components/loading', Record<never, never>, Record<never, never>>,
    '/home/about/': RouteRecordInfo<'/home/about/', '/home/about', Record<never, never>, Record<never, never>>,
    '/home/about/components/info': RouteRecordInfo<'/home/about/components/info', '/home/about/components/info', Record<never, never>, Record<never, never>>,
    '/home/about/components/intro': RouteRecordInfo<'/home/about/components/intro', '/home/about/components/intro', Record<never, never>, Record<never, never>>,
    '/home/contact/': RouteRecordInfo<'/home/contact/', '/home/contact', Record<never, never>, Record<never, never>>,
    '/home/resume/': RouteRecordInfo<'/home/resume/', '/home/resume', Record<never, never>, Record<never, never>>,
    '/home/work/': RouteRecordInfo<'/home/work/', '/home/work', Record<never, never>, Record<never, never>>,
    '/home/work/components/experience/': RouteRecordInfo<'/home/work/components/experience/', '/home/work/components/experience', Record<never, never>, Record<never, never>>,
    '/home/work/components/project/': RouteRecordInfo<'/home/work/components/project/', '/home/work/components/project', Record<never, never>, Record<never, never>>,
    '/love/': RouteRecordInfo<'/love/', '/love', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/bigScreen/index.vue': {
      routes: '/bigScreen/'
      views: never
    }
    'src/pages/bigScreen/comments/mapScene/index.vue': {
      routes: '/bigScreen/comments/mapScene/'
      views: never
    }
    'src/pages/bigScreen/comments/mCountCard/index.vue': {
      routes: '/bigScreen/comments/mCountCard/'
      views: never
    }
    'src/pages/bigScreen/comments/mHeader/index.vue': {
      routes: '/bigScreen/comments/mHeader/'
      views: never
    }
    'src/pages/bigScreen/comments/mMenu/index.vue': {
      routes: '/bigScreen/comments/mMenu/'
      views: never
    }
    'src/pages/bigScreen/comments/mMenuItem/index.vue': {
      routes: '/bigScreen/comments/mMenuItem/'
      views: never
    }
    'src/pages/blog/creativity/calendar/index.vue': {
      routes: '/blog/creativity/calendar/'
      views: never
    }
    'src/pages/blog/creativity/calendar/left.vue': {
      routes: '/blog/creativity/calendar/left'
      views: never
    }
    'src/pages/blog/creativity/calendar/right.vue': {
      routes: '/blog/creativity/calendar/right'
      views: never
    }
    'src/pages/blog/creativity/clock/index.vue': {
      routes: '/blog/creativity/clock/'
      views: never
    }
    'src/pages/blog/creativity/clock/components/left.vue': {
      routes: '/blog/creativity/clock/components/left'
      views: never
    }
    'src/pages/blog/creativity/clock/components/right.vue': {
      routes: '/blog/creativity/clock/components/right'
      views: never
    }
    'src/pages/blog/creativity/muYu/index.vue': {
      routes: '/blog/creativity/muYu/'
      views: never
    }
    'src/pages/blog/dev/jsonFormatter/index.vue': {
      routes: '/blog/dev/jsonFormatter/'
      views: never
    }
    'src/pages/blog/dev/jsonToTypeScript/index.vue': {
      routes: '/blog/dev/jsonToTypeScript/'
      views: never
    }
    'src/pages/blog/media/av/index.vue': {
      routes: '/blog/media/av/'
      views: never
    }
    'src/pages/blog/media/av/site_btn.vue': {
      routes: '/blog/media/av/site_btn'
      views: never
    }
    'src/pages/blog/media/copywriting/index.vue': {
      routes: '/blog/media/copywriting/'
      views: never
    }
    'src/pages/blog/media/music/index.vue': {
      routes: '/blog/media/music/'
      views: never
    }
    'src/pages/blog/media/video/index.vue': {
      routes: '/blog/media/video/'
      views: never
    }
    'src/pages/blog/media/voice/index.vue': {
      routes: '/blog/media/voice/'
      views: never
    }
    'src/pages/blog/media/wallpaper/index.vue': {
      routes: '/blog/media/wallpaper/'
      views: never
    }
    'src/pages/blog/news/boxOffice/index.vue': {
      routes: '/blog/news/boxOffice/'
      views: never
    }
    'src/pages/blog/news/boxOffice/components/parse/index.vue': {
      routes: '/blog/news/boxOffice/components/parse/'
      views: never
    }
    'src/pages/blog/news/game/hok/index.vue': {
      routes: '/blog/news/game/hok/'
      views: never
    }
    'src/pages/blog/news/itNews/index.vue': {
      routes: '/blog/news/itNews/'
      views: never
    }
    'src/pages/blog/news/price/cigarette/index.vue': {
      routes: '/blog/news/price/cigarette/'
      views: never
    }
    'src/pages/blog/news/price/gold/index.vue': {
      routes: '/blog/news/price/gold/'
      views: never
    }
    'src/pages/blog/news/price/oil/index.vue': {
      routes: '/blog/news/price/oil/'
      views: never
    }
    'src/pages/blog/news/weather/index.vue': {
      routes: '/blog/news/weather/'
      views: never
    }
    'src/pages/blog/news/weather/components/climate/index.vue': {
      routes: '/blog/news/weather/components/climate/'
      views: never
    }
    'src/pages/blog/news/weather/components/meter/index.vue': {
      routes: '/blog/news/weather/components/meter/'
      views: never
    }
    'src/pages/blog/news/weather/components/passedChart/index.vue': {
      routes: '/blog/news/weather/components/passedChart/'
      views: never
    }
    'src/pages/blog/news/weather/components/tempChart/index.vue': {
      routes: '/blog/news/weather/components/tempChart/'
      views: never
    }
    'src/pages/blog/socialEngineering/account/index.vue': {
      routes: '/blog/socialEngineering/account/'
      views: never
    }
    'src/pages/blog/socialEngineering/complain/index.vue': {
      routes: '/blog/socialEngineering/complain/'
      views: never
    }
    'src/pages/blog/socialEngineering/domain/index.vue': {
      routes: '/blog/socialEngineering/domain/'
      views: never
    }
    'src/pages/blog/socialEngineering/licensePlate/index.vue': {
      routes: '/blog/socialEngineering/licensePlate/'
      views: never
    }
    'src/pages/blog/socialEngineering/logistic/index.vue': {
      routes: '/blog/socialEngineering/logistic/'
      views: never
    }
    'src/pages/blog/socialEngineering/loveSpeech/index.vue': {
      routes: '/blog/socialEngineering/loveSpeech/'
      views: never
    }
    'src/pages/blog/test/api/index.vue': {
      routes: '/blog/test/api/'
      views: never
    }
    'src/pages/blog/test/component/index.vue': {
      routes: '/blog/test/component/'
      views: never
    }
    'src/pages/blog/tool/codec/base64/index.vue': {
      routes: '/blog/tool/codec/base64/'
      views: never
    }
    'src/pages/blog/tool/codec/base64/modal.vue': {
      routes: '/blog/tool/codec/base64/modal'
      views: never
    }
    'src/pages/blog/tool/codec/md5/index.vue': {
      routes: '/blog/tool/codec/md5/'
      views: never
    }
    'src/pages/blog/tool/codec/morse/index.vue': {
      routes: '/blog/tool/codec/morse/'
      views: never
    }
    'src/pages/blog/tool/codec/morse/modal.vue': {
      routes: '/blog/tool/codec/morse/modal'
      views: never
    }
    'src/pages/blog/tool/network/dns/index.vue': {
      routes: '/blog/tool/network/dns/'
      views: never
    }
    'src/pages/blog/tool/network/http/index.vue': {
      routes: '/blog/tool/network/http/'
      views: never
    }
    'src/pages/blog/tool/qrcode/index.vue': {
      routes: '/blog/tool/qrcode/'
      views: never
    }
    'src/pages/blog/workbench/index.vue': {
      routes: '/blog/workbench/'
      views: never
    }
    'src/pages/blog/workbench/MapChart.vue': {
      routes: '/blog/workbench/MapChart'
      views: never
    }
    'src/pages/blog/workbench/测试/MapChart copy 3.vue': {
      routes: '/blog/workbench/测试/MapChart copy 3'
      views: never
    }
    'src/pages/command/identityQuery/detail/index.vue': {
      routes: '/command/identityQuery/detail/'
      views: never
    }
    'src/pages/command/identityQuery/result/index.vue': {
      routes: '/command/identityQuery/result/'
      views: never
    }
    'src/pages/command/identityQuery/search/index.vue': {
      routes: '/command/identityQuery/search/'
      views: never
    }
    'src/pages/command/login/index.vue': {
      routes: '/command/login/'
      views: never
    }
    'src/pages/error/403/index.vue': {
      routes: '/error/403/'
      views: never
    }
    'src/pages/error/404/index.vue': {
      routes: '/error/404/'
      views: never
    }
    'src/pages/error/500/index.vue': {
      routes: '/error/500/'
      views: never
    }
    'src/pages/error/redirect/index.vue': {
      routes: '/error/redirect/'
      views: never
    }
    'src/pages/garage/index.vue': {
      routes: '/garage/'
      views: never
    }
    'src/pages/garage/threeContainer/index.vue': {
      routes: '/garage/threeContainer/'
      views: never
    }
    'src/pages/garage/threeContainer/index copy.vue': {
      routes: '/garage/threeContainer/index copy'
      views: never
    }
    'src/pages/garage/threeContainer/index copy 2.vue': {
      routes: '/garage/threeContainer/index copy 2'
      views: never
    }
    'src/pages/garage/threeContainer copy 2/index.vue': {
      routes: '/garage/threeContainer copy 2/'
      views: never
    }
    'src/pages/garage/uiContainer/index.vue': {
      routes: '/garage/uiContainer/'
      views: never
    }
    'src/pages/garage/uiContainer/components/bar/index.vue': {
      routes: '/garage/uiContainer/components/bar/'
      views: never
    }
    'src/pages/garage/uiContainer/components/loading/index.vue': {
      routes: '/garage/uiContainer/components/loading/'
      views: never
    }
    'src/pages/home/about/index.vue': {
      routes: '/home/about/'
      views: never
    }
    'src/pages/home/about/components/info.vue': {
      routes: '/home/about/components/info'
      views: never
    }
    'src/pages/home/about/components/intro.vue': {
      routes: '/home/about/components/intro'
      views: never
    }
    'src/pages/home/contact/index.vue': {
      routes: '/home/contact/'
      views: never
    }
    'src/pages/home/resume/index.vue': {
      routes: '/home/resume/'
      views: never
    }
    'src/pages/home/work/index.vue': {
      routes: '/home/work/'
      views: never
    }
    'src/pages/home/work/components/experience/index.vue': {
      routes: '/home/work/components/experience/'
      views: never
    }
    'src/pages/home/work/components/project/index.vue': {
      routes: '/home/work/components/project/'
      views: never
    }
    'src/pages/love/index.vue': {
      routes: '/love/'
      views: never
    }
    'src/pages/test/index.vue': {
      routes: '/test/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
